Repository FBS-UNA/SCT_FRONTEND, pull requests merged in 2023-04, with the labels that each got.

#39 Hotfix - ALPHA 1.2.3
  src/app/SCT/components/aed-area/aed-area.component.html
  src/app/SCT/components/aed-area/aed-area.component.ts
  src/app/SCT/components/aed-tramite/aed-tramite.component.html
  src/app/SCT/components/cr-registro-tramite/cr-registro-tramite.component.ts
  src/app/SCT/components/formulario-registro-entrada/formulario-registro-entrada.component.html
  src/app/SCT/components/formulario-registro-entrada/formulario-registro-entrada.component.ts
  src/app/SCT/components/formulario-registro-tramite/formulario-registro-tramite.component.html
  src/app/SCT/components/formulario-registro-tramite/formulario-registro-tramite.component.ts
  src/app/SCT/components/tabla-areas/tabla-areas.component.ts
  src/app/SCT/components/tabla-tramites/tabla-tramites.component.ts
  src/app/SCT/pages/inicio/inicio.component.html
  src/app/SCT/pages/registro-tramite/registro-tramite.component.html
  src/app/SCT/services/tramites.service.ts
  src/app/shared/sidebar/sidebar.component.css
  src/app/shared/sidebar/sidebar.component.ts
Labels: bug, enhancement

#62 Hotfix
  src/app/SCT/components/formulario-registro-entrada/formulario-registro-entrada.component.ts
  src/app/SCT/components/formulario-registro-tramite/formulario-registro-tramite.component.ts
  src/app/SCT/services/tramites.service.ts
Labels: bug

#64 Feature_mostrar_usuarios closed #63
  src/app/SCT/pages/asignacion-roles/asignacion-roles.component.html
  src/app/SCT/pages/asignacion-roles/asignacion-roles.component.ts
  src/app/SCT/services/usuarios.service.ts
Labels: user story

#67 Feature dialog editar
  src/app/SCT/components/e-usuario/e-usuario.component.html
  src/app/SCT/components/e-usuario/e-usuario.component.ts
  src/app/SCT/components/tabla-asignacion-roles/tabla-asignacion-roles.component.html
  src/app/SCT/components/tabla-asignacion-roles/tabla-asignacion-roles.component.ts
  src/app/SCT/sct.module.ts
Labels: Update

#68 Se quita el icono de de la columna de roles
  src/app/SCT/components/tabla-asignacion-roles/tabla-asignacion-roles.component.html
  src/app/SCT/components/tabla-asignacion-roles/tabla-asignacion-roles.component.ts
Labels: Update

#70 Feature_Servicio_Roles
  src/app/SCT/interfaces/roles.interface.ts
  src/app/SCT/services/roles.service.ts
Labels: Update

#73 Función Filtros Tabla Asignación Roles
  src/app/SCT/components/tabla-asignacion-roles/tabla-asignacion-roles.component.html
  src/app/SCT/components/tabla-asignacion-roles/tabla-asignacion-roles.component.ts
  src/app/SCT/interfaces/table.interface.ts
Labels: Update

#72 Feature multiselect dialog editar usuario
  src/app/SCT/components/e-usuario/e-usuario.component.html
  src/app/SCT/components/e-usuario/e-usuario.component.ts
  src/app/SCT/components/tabla-asignacion-roles/tabla-asignacion-roles.component.ts
  src/app/prime-ng/prime-ng.module.ts
Labels: Update

#77 Trámite Por Areas Registro Tramite
  src/app/SCT/components/formulario-registro-tramite/formulario-registro-tramite.component.html
  src/app/SCT/components/formulario-registro-tramite/formulario-registro-tramite.component.ts
  src/app/SCT/interfaces/area.interface.ts
  src/app/SCT/interfaces/registro-tramite.interface.ts
  src/app/SCT/services/areas.service.ts
Labels: user story, Update

#76 Fix Tipo Afiliacion Input
  src/app/SCT/components/formulario-registro-entrada/formulario-registro-entrada.component.ts
  src/app/SCT/components/formulario-registro-tramite/formulario-registro-tramite.component.ts
  src/app/SCT/components/tabla-reporte-tramites/tabla-reporte-tramites.component.html
  src/app/SCT/components/tabla-reporte-tramites/tabla-reporte-tramites.component.ts
  src/app/SCT/interfaces/cliente.interface.ts
  src/app/SCT/interfaces/reporte.interface.ts
  src/app/SCT/pages/reporte-tramites/reporte-tramites.component.html
  src/app/SCT/pages/reporte-tramites/reporte-tramites.component.ts
  src/app/SCT/sct-routing.module.ts
  src/app/SCT/sct.module.ts
  src/app/SCT/services/clientes.service.ts
  src/app/app.module.ts
  src/app/shared/sidebar/sidebar.component.ts
Labels: bug

#78 Hotfix estandar del reporte
  src/app/SCT/components/cr-registro-tramite/cr-registro-tramite.component.ts
  src/app/SCT/components/formulario-registro-tramite/formulario-registro-tramite.component.ts
  src/app/SCT/interfaces/registro-tramite.interface.ts
Labels: bug, Update

#80 Feature implementar tabla reportes
  src/app/SCT/components/tabla-reporte-tramites/tabla-reporte-tramites.component.html
  src/app/SCT/components/tabla-reporte-tramites/tabla-reporte-tramites.component.ts
  src/app/SCT/interfaces/reporte.interface.ts
  src/app/SCT/services/reporte.service.ts
Labels: user story

#81 Close
  src/app/SCT/components/tabla-reporte-tramites/tabla-reporte-tramites.component.html
  src/app/SCT/components/tabla-reporte-tramites/tabla-reporte-tramites.component.ts
Labels: user story
